version: '3'

services:
  mariadb:
    build:
      context: ./MariaDB/
      dockerfile: Dockerfile
    networks:
      - databasenetwork
    ports:
      - "3306:3306"
    environment:
    ###### modify this password, remember it and delete it from this file afterwards ######
      - MYSQL_ROOT_PASSWORD=lol
    container_name: mariadb
    command: bash -c "/database_user.sh"